apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  namespace: vikunja
data:
  VIKUNJA_SERVICE_FRONTENDURL: "https://vikunja.local"
  VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.local"
  VIKUNJA_DEFAULT_TIMEZONE: "Europe/Bucharest"