apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kube-prom-stack/helmrepository.yaml
  - kube-prom-stack/helmrelease.yaml
  - kube-grafana-stack/grafana-ingress.yaml
  - kube-prom-stack/prometheus-ingress.yaml
  - kube-prom-stack/servicemonitor-cert-manager.yaml
  - kube-prom-stack/podmonitor-ingress-nginx.yaml
  - dashboards
  - alerts