apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vikunja
resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - vikunja-deployment.yaml
  - vikunja-service.yaml
  - ingress.yaml
  - secretproviderclass.yaml
  - servicemonitor.yaml