apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      volumes:
        - name: vikunja-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: vikunja-akv
      containers:
        - name: vikunja
          image: vikunja/vikunja:1.0.0-rc1
          ports:
            - containerPort: 3456
          env:
            - name: VIKUNJA_DATABASE_TYPE
              value: "postgres"
            - name: VIKUNJA_DATABASE_HOST
              value: "postgres"
            - name: VIKUNJA_DATABASE_PORT
              value: "5432"
            - name: VIKUNJA_DATABASE_DATABASE
              value: "vikunja"

            - name: VIKUNJA_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: VIKUNJA_DATABASE_USER

            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: VIKUNJA_DATABASE_PASSWORD

            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: VIKUNJA_JWT_SECRET

            - name: VIKUNJA_SERVICE_FRONTENDURL
              valueFrom:
                configMapKeyRef:
                  name: vikunja-config
                  key: VIKUNJA_SERVICE_FRONTENDURL
            - name: VIKUNJA_SERVICE_PUBLICURL
              valueFrom:
                configMapKeyRef:
                  name: vikunja-config
                  key: VIKUNJA_SERVICE_PUBLICURL
            - name: VIKUNJA_DEFAULT_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: vikunja-config
                  key: VIKUNJA_DEFAULT_TIMEZONE
            - name: VIKUNJA_METRICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: vikunja-config
                  key: VIKUNJA_METRICS_ENABLED
          volumeMounts:
            - name: vikunja-secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true

